NAME := colour
SRC := 	colour \
	disp \
	colour_dispatch \
	derived \
	im_icc_transform \
	im_LCh2Lab \
	im_LCh2UCS \
	im_Lab2LCh \
	im_Lab2LabQ \
	im_Lab2LabS \
	im_Lab2XYZ \
	im_LabQ2Lab \
	im_LabQ2LabS \
	im_LabQ2disp \
	im_LabS2LabQ \
	im_LabS2Lab \
	im_lab_morph \
	im_UCS2LCh \
	im_XYZ2Lab \
	im_XYZ2Yxy \
	im_float2rad \
	im_Yxy2XYZ \
	im_XYZ2disp \
	im_dE00_fromLab \
	im_dECMC_fromLab \
	im_dE_fromLab \
	im_disp2XYZ \
	im_rad2float

include ../subdirs_common.mk
