NAME := other
SRC := cooc_funcs \
	glds_funcs \
	im_benchmark \
	im_dif_std \
	im_eye \
	im_grey \
	im_make_xy \
	im_meanstd \
	im_simcontr \
	im_sines \
	im_spatres \
	im_zone \
	other_dispatch

include ../subdirs_common.mk
