NAME := deprecated
SRC := deprecated_dispatch \
	im_fav4 \
	im_gadd \
	im_gaddim \
	im_cmulnorm \
	im_printlines \
	im_convsub \
	im_line \
	im_resize_linear \
	im_debugim \
	im_gfadd \
	im_setbox \
	rename \
	im_bernd \
	im_thresh \
	im_slice \
	im_print \
	im_litecor

include ../subdirs_common.mk
