NAME := freq_filt
SRC := fft_sp \
	fmask4th \
	im_phasecor_fft \
	fmaskcir \
	freq_dispatch \
	im_disp_ps \
	im_fractsurf \
	im_freq_mask \
	im_freqflt \
	im_fwfft \
	im_invfft \
	im_invfftr \
	im_rotquad

include ../subdirs_common.mk
