NAME := convolution
SRC := convol_dispatch \
	im_addgnoise \
	im_compass \
	im_conv \
	im_conv_f \
	im_convsep \
	im_convsep_f \
	im_contrast_surface \
	im_fastcor \
	im_gradcor \
	im_sharpen \
	im_spcor 

include ../subdirs_common.mk
