NAME := arithmetic
SRC := arith_dispatch \
	im_abs \
	im_add \
	im_avg \
	im_bandmean \
	im_cross_phase \
	im_deviate \
	im_divide \
	im_recomb \
	im_invert \
	im_linreg \
	im_lintra \
	im_maxpos_avg \
	im_maxpos \
	im_maxpos_vec \
	im_measure \
	im_minpos \
	im_multiply \
	im_point_bilinear \
	im_remainder \
	im_sign \
	im_stats \
	im_subtract \
	math \
	power \
	round

include ../subdirs_common.mk
