NAME := format
SRC := format \
	format_dispatch \
	im_analyze2vips \
	im_csv2vips \
	im_exr2vips \
	im_jpeg2vips \
	im_magick2vips \
	im_png2vips \
	im_ppm2vips \
	im_raw2vips \
	im_tiff2vips \
	im_tile_cache \
	im_vips2csv \
	im_vips2jpeg \
	im_vips2png \
	im_vips2ppm \
	im_vips2tiff \
	im_vips2raw \
	matlab \
	radiance 

include ../subdirs_common.mk
