NAME := mosaicing
SRC := im_align_bands \
	match \
	mosaic1  \
	mosaicing_dispatch \
	global_balance \
	im_avgdxdy \
	im_chkpair \
	im_clinear \
	im_improve \
	im_initialize \
	im_lrcalcon \
	im_lrmerge \
	im_lrmosaic \
	im_maxpos_subpel \
	im_tbcalcon \
	im_tbmerge \
	im_remosaic \
	im_tbmosaic \

include ../subdirs_common.mk
