NAME := histograms_lut
SRC := hist_dispatch \
	im_gammacorrect \
	im_heq \
	im_hist \
	im_histeq \
	im_histgr \
	im_histnD \
	im_histplot \
	im_histindexed \
	im_histspec \
	im_hsp \
	im_mpercent \
	im_identity \
	im_invertlut \
	im_lhisteq \
	im_maplut \
	im_buildlut \
	im_project \
	im_stdif \
	tone

include ../subdirs_common.mk
