NAME := conversion
SRC := conver_dispatch \
	im_black \
	im_c2amph \
	im_c2rect \
	im_c2imag \
	im_c2real \
	im_clip2fmt \
	im_copy \
	im_copy_file \
	im_extract \
	im_falsecolour \
	im_fliphor \
	im_flipver \
	im_gbandjoin \
	im_embed \
	im_insert \
	im_lrjoin \
	im_mask2vips \
	im_msb \
	im_replicate \
	im_grid \
	im_ri2c \
	im_rot180 \
	im_rot270 \
	im_rot90 \
	im_scale \
	im_scaleps \
	im_subsample \
	im_system \
	im_system_image \
	im_tbjoin \
	im_text \
	im_gaussnoise \
	im_vips2mask \
	im_wrap \
	im_zoom

CFLAGS += -DHAVE_RAND
CXXFLAGS += -DHAVE_RAND

include ../subdirs_common.mk
