NAME := resample
SRC := im_affine \
	interpolate \
	im_shrink \
	im_stretch3 \
	im_rightshift_size \
	transform \
	resample_dispatch \
	bicubic \
	lbb \
	nohalo \
	vsqbs

include ../subdirs_common.mk
