NAME := RTTL
SRC := BVH/BVH \
    BVH/Builder/Builder \
    BVH/Builder/Sweep \
    BVH/Builder/BinnedAllDims \
    BVH/Builder/BinnedAllDimsSaveSpace \
    BVH/Builder/OnDemandBuilder \
    common/RTThread \
    common/MapOptions \
    API/ISG

SUB_DIRS := BVH/Builder common API

LIBS += -lstdc++

include ../subdirs_common.mk
